<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ManagementLabel</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Components\Layout\CarouselSlide.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CarouselSlide.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\CustomDropdownLayout.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CustomDropdownLayout.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\CustomersPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CustomersPage.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\DebtPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DebtPage.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\Discountcode.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Discountcode.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\DistributionLinesPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DistributionLinesPage.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\InvoiceLayout.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>InvoiceLayout.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\NavMenu.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NavMenu.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\OneTimePaymentsPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OneTimePaymentsPage.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\Orders.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Orders.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\OverlayEditAddCustomers.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OverlayEditAddCustomers.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\OverlayEditAddFormOneTimePayment.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OverlayEditAddFormOneTimePayment.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\PGruppeCatPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PGruppeCatPage.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\ProductsManagement.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProductsManagement.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\SuppliersPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SuppliersPage.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Layout\UsersPage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UsersPage.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Components\Layout\CarouselSlide.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CarouselSlide.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\CustomDropdownLayout.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CustomDropdownLayout.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\CustomersPage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CustomersPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\DebtPage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DebtPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\Discountcode.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Discountcode.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\DistributionLinesPage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DistributionLinesPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\InvoiceLayout.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>InvoiceLayout.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\NavMenu.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\NavMenu.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\NavMenu.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NavMenu.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\OneTimePaymentsPage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OneTimePaymentsPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\Orders.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Orders.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\OverlayEditAddCustomers.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OverlayEditAddCustomers.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\OverlayEditAddFormOneTimePayment.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OverlayEditAddFormOneTimePayment.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\PGruppeCatPage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PGruppeCatPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\ProductsManagement.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ProductsManagement.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\SuppliersPage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SuppliersPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Layout\UsersPage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UsersPage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
